version: '3.7'

services:

  db:
    image: postgres:13
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: 'postgres'
      PGDATA: '/var/lib/postgresql/data'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - /home/dma/06-db-04-postgresql/data:/var/lib/postgresql/data
      - /home/dma/06-db-04-postgresql/backup:/var/lib/postgresql/backup
    ports:
      - '5432:5432'
