version: '3.7'

services:

  db:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'test_db'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'mysql'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - /home/dma/06-db-03-mysql/data:/var/lib/mysql
      - /home/dma/06-db-03-mysql/backup:/backup
    ports:
      - '3306:3306'
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db      
    ports:
      - '8080:8080'
