version: '3.7'

services:
  postgres:
    build: ./postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 1408:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 12345